<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Category Management</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container my-4">
    <!-- Page Header -->
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1>Category Management</h1>
        <a href="adminDashboard.jsp" class="btn btn-secondary">Back to Dashboard</a>
    </div>

    <!-- Category Form -->
    <%
        // Check if "action" and "id" parameters exist
        String action = request.getParameter("action");
        String categoryId = request.getParameter("id");
        String categoryName = request.getParameter("name");

        boolean isEdit = action != null && action.equals("edit");
    %>

    <div class="card mb-4">
        <div class="card-header">
            <%= isEdit ? "Edit Category" : "Add New Category" %>
        </div>
        <div class="card-body">
            <form action="CategoryServlet" method="post">
                <% if (isEdit) { %>
                <input type="hidden" name="id" value="<%= categoryId %>">
                <% } %>
                <div class="mb-3">
                    <label for="name" class="form-label">Category Name</label>
                    <input type="text" class="form-control" id="name" name="name" value="<%= isEdit ? categoryName : "" %>" required>
                </div>
                <button type="submit" class="btn btn-success"><%= isEdit ? "Update Category" : "Add Category" %></button>
                <% if (isEdit) { %>
                <a href="categoryManagement.jsp" class="btn btn-secondary">Cancel</a>
                <% } %>
            </form>
        </div>
    </div>

    <!-- Category List -->
    <h2>Category List</h2>
    <table class="table table-striped">
        <thead class="table-dark">
        <tr>
            <th>#</th>
            <th>Category Name</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <%-- Example row (dynamic content should be generated by the servlet or backend logic) --%>
        <tr>
            <td>1</td>
            <td>Example Category</td>
            <td>
                <a href="CategoryManagement.jsp?action=edit&id=1&name=Example Category"
                   class="btn btn-sm btn-warning">Edit</a>
                <a href="CategoryServlet?action=delete&id=1" class="btn btn-sm btn-danger">Delete</a>
            </td>
        </tr>
        <%-- Add dynamic rows here from the backend --%>
        </tbody>
    </table>
</div>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
