<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Management</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container my-4">
    <!-- Page Header -->
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1>Product Management</h1>
        <a href="adminDashboard.jsp" class="btn btn-secondary">Back to Dashboard</a>
    </div>

    <!-- Product Form -->
    <%
        // Check if "action" and "id" parameters exist
        String action = request.getParameter("action");
        String productId = request.getParameter("id");
        String productName = request.getParameter("name");
        String qty = request.getParameter("qty");
        String productCategory = request.getParameter("category");
        String productPrice = request.getParameter("price");

        boolean isEdit = action != null && action.equals("edit");
    %>

    <div class="card mb-4">
        <div class="card-header">
            <%= isEdit ? "Edit Product" : "Add New Product" %>
        </div>
        <div class="card-body">
            <form action="ProductServlet" method="post" enctype="multipart/form-data">
                <% if (isEdit) { %>
                <input type="hidden" name="id" value="<%= productId %>">
                <% } %>
                <div class="mb-3">
                    <label for="name" class="form-label">Product Name</label>
                    <input type="text" class="form-control" id="name" name="name" value="<%= isEdit ? productName : "" %>" required>
                </div>
                <div class="mb-3">
                    <label for="category" class="form-label">Category</label>
                    <input type="text" class="form-control" id="category" name="category" value="<%= isEdit ? productCategory : "" %>" required>
                </div>
                <div class="mb-3">
                    <label for="qty" class="form-label">Quantity</label>
                    <input type="text" class="form-control" id="qty" name="category" value="<%= isEdit ? qty : "" %>" required>
                </div>
                <div class="mb-3">
                    <label for="price" class="form-label">Price ($)</label>
                    <input type="number" class="form-control" id="price" name="price" value="<%= isEdit ? productPrice : "" %>" required>
                </div>
                <div class="mb-3">
                    <label for="image" class="form-label">Product Image</label>
                    <input type="file" class="form-control" id="image" name="image" accept="image/*" <% if (!isEdit) { %> required <% } %>>
                </div>
                <button type="submit" class="btn btn-success"><%= isEdit ? "Update Product" : "Add Product" %></button>
                <% if (isEdit) { %>
                <a href="ProductManagement.jsp" class="btn btn-secondary">Cancel</a>
                <% } %>
            </form>
        </div>
    </div>

    <!-- Product List -->
    <h2>Product List</h2>
    <table class="table table-striped">
        <thead class="table-dark">
        <tr>
            <th>#</th>
            <th>Image</th>
            <th>Product Name</th>
            <th>Category</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <%-- Example row (dynamic content should be generated by the servlet or backend logic) --%>
        <tr>
            <td>1</td>
            <td><img src="uploads/example.jpg" alt="Product Image" style="width: 50px; height: 50px;"></td>
            <td>Example Product</td>
            <td>Example Category</td>
            <td>$100</td>
            <td>
                <a href="ProductManagement.jsp?action=edit&id=1&name=Example Product&category=Example Category&price=100"
                   class="btn btn-sm btn-warning">Edit</a>
                <a href="ProductServlet?action=delete&id=1" class="btn btn-sm btn-danger">Delete</a>
            </td>
        </tr>
        <%-- Add dynamic rows here from the backend --%>
        </tbody>
    </table>
</div>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
